### ISSUE TITLE
Suggested edits to ReadMe and one error correction.

### ISSUE THREAD

**Issue by Steve-Z** [joelparkerhenderson/demo-rust-axum#11]
In the section "Respond with HTTP status code OK" by importing as you suggest:
```
use axum::{
    …
    http::StatusCode,
};
```
the code `axum::http::StatusCode` or `axum::http::StatusCode::OK` becomes redundant and can be replaced with `StatusCode` and `StatusCode::OK`, respectively.

Also, after the `axum::http::StatusCode` import, the code In the previous "Fallback" section `axum::http::StatusCode::NOT_FOUND` can then be replaced with `StatusCode::NOT_FOUND`.

Likewise, you suggest importing
```
use axum::{
    …
    response::Html,
};
```
which similarly obviates the need for the full path imports `axum::response::Html` which can be simply `Html` in the "Respond with HTML text/file" sections.

So far I have only gone as far as the HTML verbs section. There may be more cases similar to those above. I also noticed that `use axum::handler::Handler;` is not necessary in the fallback section. I noticed these because either the compiler or Clippy has flagged "unused import" when I copied from your example code.

Lastly, in the "Respond with custom header and image" section, this code
```
base64::engine::general_purpose::STANDARD::decode(png).unwrap()
```
seems to have a typo. It should be
```
base64::engine::general_purpose::STANDARD.decode(png).unwrap()
```
ie, it's STANDARD[dot]decode.

Thanks you for this tutorial. It is very helpful for a newbie like me.

**Comment by joelparkerhenderson** [comment]
Thank you. Yes, you're right. 

Rust documentation in general tends to favor the "use" approach and minimally-qualified code, such as:

```rust
use axum::http::StatusCode::OK
… return OK
```

Whereas learners tend to succeed better with fully-qualified code, such as:

```rust
return axum::http::StatusCode::OK
```

I'll take your items and change them from "use" to fully-qualified code.

Good catch on the dot decode typo. The source code file is correct, and I'll fix that README file now.

If you see more items, please do let me know. Same if you have ideas that you would like the demo to cover. Your feedback is very much appreciated!
