### ISSUE TITLE
Post book and Delete book format!(...) does not match "Output" in the Readme

### ISSUE THREAD

**Issue by Steve-Z** [joelparkerhenderson/demo-rust-axum#15]
Minor point here but in Post book
```
pub async fn post_books_id_form(
    ...
            format!("<p>{}</p>\n", &new_book)
...
}
```
Does not produce the Output described in the Readme:
`Post book: Another Title by Someone Else`

And similarly in Delete...
```
pub async fn delete_books_id(
...
            format!("Delete book id: {}", &id)
...
}
```
does not match Readme:
`<p>Delete book id: 1</p>`

**Comment by joelparkerhenderson** [comment]
Thank you.

For the first item, I'm fixing README.md:

```
-            format!("<p>{}</p>\n", &new_book)
+            format!("Post book: {}", &new_book)
```

For the second item, where are you seeing the delete output differ? For example, are you seeing the difference in the epub book, the pdf book, the top level README.md, the restful example, or somewhere else?

**Comment by joelparkerhenderson** [comment]
Thank you. Good catch! I've just fixed both and pushed.
