### ISSUE TITLE
"Add a Tower tracing subscriber" is not working

### ISSUE THREAD

**Issue by edpyt** [joelparkerhenderson/demo-rust-axum#19]
Following the steps from [Add a Tower tracing subscriber](https://github.com/joelparkerhenderson/demo-rust-axum?tab=readme-ov-file#add-a-tower-tracing-subscriber) I'm not getting the expected output: \
![image](https://github.com/user-attachments/assets/d4e92e82-7b7c-44b4-83d0-b348aee09103) \
![image](https://github.com/user-attachments/assets/b5ec07b8-5641-44a9-9c57-de2e2632cdab) \
![image](https://github.com/user-attachments/assets/7a5cf8e4-60dc-43d3-b717-4a618be1c4b4)

**Comment by joelparkerhenderson** [comment]
Thank you for reporting this. I'll look into it.

Can you try this simpler project, and let me know if it runs successfully for you?

https://github.com/joelparkerhenderson/demo-rust-axum-tracing-subscriber

**Comment by edpyt** [comment]
Oh, I see. Now it works, thank you! \
![image](https://github.com/user-attachments/assets/6ee5489c-1b88-45a8-830e-f72fefe4c3f3)
