### ISSUE TITLE
Add-a-tower-tracing-subscriber doesn't output the tracing initialization

### ISSUE THREAD

**Issue by Cosmodude** [joelparkerhenderson/demo-rust-axum#21]
https://github.com/joelparkerhenderson/demo-rust-axum?tab=readme-ov-file#add-a-tower-tracing-subscriber

followed the steps, 

but couldn't see the init logs, like this:

```2022-03-08T00:13:54.483877Z
    TRACE mio::poll:
    registering event source with poller:
    token=Token(1),
    interests=READABLE | WRITABLE
    ```

**Comment by joelparkerhenderson** [comment]
Tower has changed somewhat; I'll push an update now. 

What happens when you run this?

```sh
git pull
cargo update
cd src
cargo run
```

You should see tracing output such as:

```sh
2024-11-12T19:57:53.841782Z  INFO demo_rust_axum: main
```

**Comment by Cosmodude** [comment]
Works now, got such input :

```2024-11-13T03:50:35.988176Z  INFO book: main```

with this code:

```tracing_subscriber::registry()
        .with(tracing_subscriber::fmt::layer())
        .init();
    tracing::event!(tracing::Level::INFO, "main");
    ```
