### ISSUE TITLE
"Post one book as a web form" 

### ISSUE THREAD

**Issue by robotnix5** [joelparkerhenderson/demo-rust-axum#3]
The code compiled fine for this section, but running 
```
curl \
--request POST 'http://localhost:3000/books/1' \
--header "Content-Type: application/json" \
--data '{"id":"1","title":"Another Title","author":"Someone Else"}'
```

produced no output. 

Further, `curl 'http://localhost:3000/books'` produced:

```html
<p>Antigone by Sophocles</p>
<p>Beloved by Toni Morrison</p>
<p>Candide by Voltaire</p>
```

Is there an error in the tutorial I am not catching?

**Comment by timeday1102** [comment]
Yes, i  think there is something wrong here.
The curl command that should be：
```
curl \
--request POST '127.0.0.1:3000/books/1/form' \
--header "Content-Type: application/x-www-form-urlencoded" 
--data 'id=1&title=Another Title&author=Someine Else'
```
and the output should be:
```
<p>Another Title by Someine Else</p>
```
after, `curl 'http://localhost:3000/books' `produced：
```
<p>Another Title by Someine Else</p>
<p>Beloved by Toni Morrison</p>
<p>Candide by Voltaire</p>
```

**Comment by joelparkerhenderson** [comment]
Thank you both! Yes, you're correct. I apologize for the long delay-- this issue slipped under the radar. I'm updating it now.
